### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by farseer90718** [JerryLead/SparkInternals#34]
pdf版本的实际显示效果为黑体于楷体混合，影响观感。

![2015-08-04-145043_984x337_scrot](https://cloud.githubusercontent.com/assets/568457/9055039/8196d0c8-3ab9-11e5-8fcf-1cec14adfff1.png)

是否可以更改下字体设置？

**Comment by JerryLead** [comment]
我用MacOS上的Chrome生成的PDF，而且这里的PDF版本比较旧了，建议使用markdown阅读或者使用下面的方法适合你的操作系统的PDF版本

PDF版生成方法是：
1. 裁剪HTML：使用chrome的Develop tools去除不必要的html标签，只保留html里面的文字和图片内容
2. 打印出PDF：使用Ctrl+P，将裁剪后的html打印成pdf保存到电脑

**Comment by farseer90718** [comment]
谢答复，我试试。
