### ISSUE TITLE
readme.md的content目录，英文版的link不统一

### ISSUE THREAD

**Issue by keypointt** [JerryLead/SparkInternals#44]
readme.md的content目录

前三章是：`master/EnglishVersion/xxx.md`

第四章开始是：`master/markdown/english/xxx.md`

似乎应该删掉其中一个，全部放到一个地方，没有重复的文件

如果能确定删掉哪一个文件夹，我可以提交一个PR :smile:

**Comment by JerryLead** [comment]
不好意思，这么晚才回复，由于英文版的是朋友帮忙翻译的，前三章我已经review过了，放在了EnglishVersion目录下，后面的我还没有review，所以暂时还在markdown/english下面

**Comment by keypointt** [comment]
好的。多谢！
